obj-m += fifoproc.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

install:
	insmod fifoproc.ko

uninstall:
	rmmod fifoproc

